name: 'fastpages: Blogging With Jupyter Notebooks & Word Docs for GitHub Pages'
description: Converts Jupyter notebooks and Word docs into Jekyll blog posts
author: Hamel Husain
inputs:
  BOOL_SAVE_MARKDOWN:
    description: Either 'true' or 'false'.  Whether or not to commit converted markdown files from notebooks and word documents into the _posts directory in your repo.  This is useful for debugging.
    required: false
    default: false
  SSH_DEPLOY_KEY:
    description: a ssh deploy key is required if BOOL_SAVE_MARKDOWN = 'true'
    required: false
  BOOL_FREE_STRUCTURE:
    description: Either 'true' or 'false'.  Whether or not to consider all notebooks which are not necessarily located in _notebooks dir to be converted. If set to 'true' the generated markdown files will be located in the same source directory. This is useful for static website generators other than Jekyll.
    required: false
    default: false
  BOOL_FORCE_DATE:
    description: Either 'true' or 'false'.  Whether or not to force the date prefix for the markdown generated files from the notebooks.
    required: false
    default: true
branding:
  color: 'blue'
  icon: 'book'
runs:
  using: 'docker'
  image: '_action_files/Dockerfile'
